<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>uws</string>
	</array>
	<key>name</key>
	<string>UWSC</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?-m)(//).*\n?</string>
			<key>name</key>
			<string>comment.line.uwsc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.uwsc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)&lt;#(CR|DBL|TAB)&gt;</string>
					<key>name</key>
					<string>string.interpolated.uwsc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>numbers</string>
			<key>match</key>
			<string>\b\d+(\.\d+)?\b</string>
			<key>name</key>
			<string>constant.numeric.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>hex numbers</string>
			<key>match</key>
			<string>\$[0-9A-Fa-f]+\b</string>
			<key>name</key>
			<string>constant.numeric.hex.uwsc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(TRUE|FALSE|NULL|EMPTY|NOTHING)\b</string>
			<key>name</key>
			<string>constant.language.uwsc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(EVENT_PRM|PARAM_STR|ALL_ITEM_LIST|ALL_OLE_ITEM|ALL_WIN_ID|ALL_IMG_[XY]|GETDIR_FILES)\b)</string>
			<key>name</key>
			<string>variable.parameter.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>GETID</string>
			<key>match</key>
			<string>(?i:\bGET_((ACTIVE|FROMPOINT|THISUWSC|LOGPRINT|FUKIDASI|BALLOON|SCHEDULE)_WIN|FROMPOINT_OBJ|FORM_WIN2?)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>CLKITEM</string>
			<key>match</key>
			<string>(?i:\bCLK_(BTN|LIST|TAB|MENU|TREEVEW|TREEVIEW|LSTVEW|LISTVIEW|TOOLBAR|ACC|SHORT|BACK|MUSMOVE|RIGHTCLK|LEFTCLK|DBLCLK|FROMLAST|CONTINUE)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>CTRLWIN</string>
			<key>match</key>
			<string>(?i:\b(ACTIVATE|CLOSE|CLOSE2|HIDE|SHOW|MIN|MAX|NORMAL|TOPMOST|NOTOPMOST|TOPNOACTV)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>SENDSTR GETSTR</string>
			<key>match</key>
			<string>(?i:\bSTR_(ACC_EDIT|ACC_STATIC|EDIT|STATIC|STATUS|ACC_CELL)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>GETITEM</string>
			<key>match</key>
			<string>(?i:\bITM_(BTN|LIST|TAB|MENU|TREEVI?EW|LISTVIEW|LSTVEW|EDIT|STATIC|STATUSBAR|TOOLBAR|ACC(CLK2?|TXT|EDIT)|FROMLAST|BACK)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>SETSLIDER GETSLIDER</string>
			<key>match</key>
			<string>(?i:\b(SLD_(POS|MIN|MAX|PAGE|BAR|X|Y)|GET_SLIDER)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>STATUS</string>
			<key>match</key>
			<string>(?i:\bST_(TITLE|CLASS|X|Y|WIDTH|HEIGHT|CLX|CLY|CLWIDTH|CLHEIGHT|PARENT|ICON|MAXIMIZED|VISIBLE|ACTIVE|BUSY|ISID|WIN64|PATH|PROCESS|MONITOR)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>PEEKCOLOR</string>
			<key>match</key>
			<string>(?i:\bCOL_([RGB]|RGB)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>CHKIMG SAVEIMG</string>
			<key>match</key>
			<string>(?i:\b(G_IMG_[XY]|IMG_MSK_([BGR]|BGR)[1-4]|IMG_(FORE|BACK))\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>MUSCUR</string>
			<key>match</key>
			<string>(?i:\bCUR_(APPSTARTING|ARROW|CROSS|HAND|HELP|IBEAM|NO|SIZEALL|SIZENESW|SIZENS|SIZENWSE|SIZEWE|UPARROW|WAIT)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>POSACC</string>
			<key>match</key>
			<string>(?i:\bACC_(ACC|API|DESCRIPTION|LOCATION|NAME|ROLE|STATE|VALUE|BACK)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>MSGBOX</string>
			<key>match</key>
			<string>(?i:\bBTN_(YES|NO|OK|CANCEL|ABORT|RETRY|IGNORE)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>SLCTBOX</string>
			<key>match</key>
			<string>(?i:\bSLCT_([1-9]|[12][0-9]|3[01]|BTN|CHK|CMB|LST|NUM|RDO|STR)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>MONITOR</string>
			<key>match</key>
			<string>(?i:\bMON_(HEIGHT|WIDTH|X|Y|NAME)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>GETTIME</string>
			<key>match</key>
			<string>(?i:\bG_TIME_((DD|HH|MM|NN|SS|ZZ|YY)2?|WW|YY4)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>POFF</string>
			<key>match</key>
			<string>(?i:\bP_(FORCE|LOGOFF|MONIPOWER[23]?|POWEROFF|REBOOT|SCREENSAVE|SHUTDOWN|SUSPEND2?|UWSC_REEXEC)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>GETKEYSTATE</string>
			<key>match</key>
			<string>(?i:\bTGL_(CAPSLOCK|IME|KANALOCK|NUMLOCK|SCROLLLOCK)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>SETHOTKEY</string>
			<key>match</key>
			<string>(?i:\b(HOTKEY_(MOD|VK)|MOD_(ALT|CONTROL|SHIFT|WIN))\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>LOCKHARDEX</string>
			<key>match</key>
			<string>(?i:\bLOCK_(KEYBOARD|MOUSE)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>GETCTLHND</string>
			<key>match</key>
			<string>(?i:\bGET_(SYS)?MENU_HND\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>VARTYPE</string>
			<key>match</key>
			<string>(?i:\bVAR_(EMPTY|NULL|SMALLINT|INTEGER|SINGLE|DOUBLE|CURRENCY|DATE|DISPATCH|ERROR|BOOLEAN|VARIANT|UNKNOWN|S?BYTE|D?WORD|INT64|[BAU]STR|ARRAY)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>BTN KBD</string>
			<key>match</key>
			<string>(?i:\b(LEFT|RIGHT|MIDDLE|WHEEL|CLICK|DOWN|UP)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>VAL COMエラー</string>
			<key>match</key>
			<string>(?i:\b(ERR_VALUE|COM_ERR_FLG)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>STRCONV</string>
			<key>match</key>
			<string>(?i:\bSC_((FULL|HALF)WIDTH|HIRAGANA|KATAKANA|(LOWER|UPPER)CASE)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>CALCARRAY</string>
			<key>match</key>
			<string>(?i:\bCALC_(ADD|MIN|MAX|AVR)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>FOPEN FGET FPUT</string>
			<key>match</key>
			<string>(?i:\bF_(READ|WRITE(8B?|16?)?|EXISTS|EXCLUSIVE|TAB|NOCR|LINECOUNT|ALLTEXT|INSERT)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>ENCODE DECODE</string>
			<key>match</key>
			<string>(?i:\bCODE_(URL|UTF8|ANSI|BYTEARRAYW?|HTML)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>CREATEFORM GETFORMDATA</string>
			<key>match</key>
			<string>(?i:\bFOM_(NO(ICON|HIDE|SUBMIT|RESIZE|LUNA|TASKBAR)|(MINI|MAXI)MIZE|BROWSER|FORMHIDE|GETVALUE|FORM2)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>SENSOR</string>
			<key>match</key>
			<string>(?i:\bSNSR_(Biometric_Human(Presense|Proximity)|Electrical_(Capacitance|Resistance|Inductance|Current|Voltage|Power)|Environmental_(Temperature|Pressure|Humidity|WindDirection|WindSpeed)|Light_(Lux|Temperature)|Mechanical_(Force|AbsPressure|GaugePressure|Weight)|Motion_(Acceleration[XYZ]|AngleAccel[XYZ]|Speed)|Scanner_(RFIDTag|BarcodeData)|Orientation_(Tilt[XYZ]|Distance[XYZ]|MagHeading|TrueHeading|CompMagHeading|CompTrueHeading)|Location_(Altitude|Latitude|Longitude|Speed))\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>QSORT</string>
			<key>match</key>
			<string>(?i:\bQSRT_(UNICODE|NATURAL)?[AD]\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>XLOPEN</string>
			<key>match</key>
			<string>(?i:\bXL_(NEW|BOOK|OOOC)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>特殊変数</string>
			<key>match</key>
			<string>(?i:\b(GET_((WIN|SYS|CUR|APPDATA|UWSC)_DIR|UWSC_(VER|PRO|NAME))|G_(MOUSE_[XY]|SCREEN_[WHC]))\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>連想配列</string>
			<key>match</key>
			<string>(?i:\bHASH_(CASECARE|EXISTS|KEY|REMOVE(ALL)?|SORT|VAL)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>TRY</string>
			<key>match</key>
			<string>(?i:\bTRY_ERR(LINE|MSG)\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Virtual KeyCode</string>
			<key>match</key>
			<string>(?i:\b(VK_([0-9A-Z]|F[1-9]|F1[0-2]|NUMPAD[0-9]|OEM_([1-8]|PA[1-3]|COMMA|JUMP|MINUS|PERIOD|PLUS|RESET)|VOLUME_(DOWN|MUTE|UP)|MEDIA_(NEXT_TRACK|PLAY_PAUSE|PREV_TRACK|STOP)|LAUNCH_(APP1|APP2|MAIL|MEDIA_SELECT)|BROWSER_(BACK|FAVORITES|FORWARD|HOME|REFRESH|SEARCH|STOP)|ACCEPT|ADD|ALT|APPS|BACK|CAPITAL|CLEAR|CONTROL|CONVERT|CTRL|DECIMAL|DELETE|DIVIDE|DOWN|END|ESC|ESCAPE|EXECUTE|FINAL|HELP|HOME|INSERT|KANA|KANJI|LBUTTON|LEFT|MBUTTON|MENU|MODECHANGE|MULTIPLY|NEXT|NONCONVERT|NUMLOCK|PAUSE|PRINT|PRIOR|RBUTTON|RCTRL|RETURN|RIGHT|RSHIFT|SCROLL|SELECT|SEPARATOR|SHIFT|SLEEP|SNAPSHOT|SPACE|START|SUBTRACT|TAB|UP|WIN))\b)</string>
			<key>name</key>
			<string>constant.other.uwsc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)option\s+(EXPLICIT|SAMESTR|OPTFINALLY|OPTPUBLIC|SPECIALCHAR|SHORTCIRCUIT|DEFAULTFONT|POSITION|LOGPATH|LOGLINES|LOGFILE|DLGTITLE|NOSTOPHOTKEY|TOPSTOPFORM)</string>
			<key>name</key>
			<string>storage.modifier.uwsc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(FOR|TO|IN|STEP|NEXT|IFB?|THEN|ELSE(IF)?|ENDIF|TRY|EXCEPT|FINALLY|ENDTRY|WITH|ENDWITH)\b)</string>
			<key>name</key>
			<string>storage.type.block.uwsc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(mod|and|or|xor)\b)</string>
			<key>name</key>
			<string>keyword.operator.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>ウィンドウ関連</string>
			<key>match</key>
			<string>(?i:\b(GETID|CLKITEM|CHKBTN|CTRLWIN|SENDSTR|GETSTR|GETITEM|GETSLCTLST|SETSLIDER|GETSLIDER|SCKEY|GETALLWIN|STATUS|MOUSEORG|PEEKCOLOR|CHKIMG|SAVEIMG|MUSCUR|POSACC)\b)</string>
			<key>name</key>
			<string>support.function.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>ダイアログ/表示関連</string>
			<key>match</key>
			<string>(?i:\b(INPUT|MSGBOX|SLCTBOX|POPUPMENU|BALLOON|FUKIDASI|STOPFORM|LOGPRINT|MONITOR)\b)</string>
			<key>name</key>
			<string>support.function.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>制御関数関連</string>
			<key>match</key>
			<string>(?i:\b(EXEC|SLEEP|DOSCMD|POWERSHELL|SOUND|GETTIME|POFF|KINDOFOS|CPUUSERATE|GETKEYSTATE|SETHOTKEY|LOCKHARD|LOCKHARDEX|EVAL|SENSOR)\b)</string>
			<key>name</key>
			<string>support.function.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>システム関数関連 ウィンドウ関数低レベル</string>
			<key>match</key>
			<string>(?i:\b(GETCTLHND|IDTOHND|HNDTOID|VARTYPE|MMV|BTN|KBD|ACW)\b)</string>
			<key>name</key>
			<string>support.function.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>文字操作関連</string>
			<key>match</key>
			<string>(?i:\b(COPYB?|POSB?|LENGTH[BS]?|CHKNUM|VAL|REPLACE|CHGMOJ|TRIM|FORMAT|CHRB?|ASCB?|ISUNICODE|STRCONV|TOKEN|BETWEENSTR)\b)</string>
			<key>name</key>
			<string>support.function.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>配列操作関連</string>
			<key>match</key>
			<string>(?i:\b(RESIZE|SETCLEAR|SHIFTARRAY|CALCARRAY|SPLIT|JOIN|SLICE|QSORT)\b)</string>
			<key>name</key>
			<string>support.function.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>ファイル関連 INIファイル</string>
			<key>match</key>
			<string>(?i:\b(FOPEN|FGET|FPUT|FDELLINE|FCLOSE|GETDIR|DROPFILE|READINI|WRITEINI|DELETEINI|DELETEFILE)\b)</string>
			<key>name</key>
			<string>support.function.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>COMオブジェクト 音声認識/合成</string>
			<key>match</key>
			<string>(?i:\b(CREATEOLEOBJ|GETACTIVEOLEOBJ|GETOLEITEM|OLEEVENT|SAFEARRAY|SPEAK|RECOSTATE|DICTATE)\b)</string>
			<key>name</key>
			<string>support.function.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>IE操作関連 フォーム画面 Excel操作関連</string>
			<key>match</key>
			<string>(?i:\b(IEGETDATA|IESETDATA|IEGETSRC|IESETSRC|IELINK|ENCODE|DECODE|CREATEFORM|GETFORMDATA|SETFORMDATA|XLOPEN|XLCLOSE|XLACTIVATE|XLSHEET|XLGETDATA|XLSETDATA)\b)</string>
			<key>name</key>
			<string>support.function.uwsc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>数学関数</string>
			<key>match</key>
			<string>(?i:\b(RANDOM|ABS|ZCUT|INT|CEIL|ROUND|SQRT|POWER|EXP|LN|LOGN|SIN|COS|TAN|ARCSIN|ARCCOS|ARCTAN)\b)</string>
			<key>name</key>
			<string>support.function.uwsc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(COM_ERR_IGN|COM_ERR_RET|EXIT|EXITEXIT|PRINT|THREAD|VAR)\b)</string>
			<key>name</key>
			<string>keyword.control.uwsc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*\b(for|while|repeat)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.loop.uwsc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*\b(next|wend|until)\b</string>
			<key>name</key>
			<string>meta.loop.uwsc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i:\b(break|continue)\b)</string>
					<key>name</key>
					<string>variable.parameter.uwsc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*\b(select)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.select.uwsc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*\b(selend)\b</string>
			<key>name</key>
			<string>meta.select.uwsc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i:\b(case|default)\b)</string>
					<key>name</key>
					<string>variable.parameter.uwsc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(procedure)\s+(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.procedure.uwsc</string>
				</dict>
			</dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.procedure.uwsc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>関数宣言部</string>
			<key>end</key>
			<string>(?i)^\s*(fend)</string>
			<key>name</key>
			<string>meta.procedure.uwsc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(function)\s+(\w+)\(</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.uwsc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.function.uwsc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>関数宣言部</string>
			<key>end</key>
			<string>(?i)^\s*(fend)</string>
			<key>name</key>
			<string>meta.function.uwsc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i:\b(RESULT)\b)</string>
					<key>name</key>
					<string>variable.parameter.uwsc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(module|class)\s+(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.module.uwsc</string>
				</dict>
			</dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.module.uwsc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*(end(module|class))</string>
			<key>name</key>
			<string>meta.module.uwsc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i:\b(this|global)\b)</string>
					<key>name</key>
					<string>variable.parameter.uwsc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.define.uwsc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>変数・定数宣言部</string>
			<key>match</key>
			<string>(?i)^\s*(DIM|PUBLIC|CONST|HASHTBL)\s+</string>
			<key>name</key>
			<string>meta.define.uwsc</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.define.uwsc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>CALL</string>
			<key>match</key>
			<string>(?i)^\s*(CALL)\s+</string>
			<key>name</key>
			<string>meta.define.uwsc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(def_dll)\s+(\w+)\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.uwsc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.uwsc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)(\s*:\s*(?i)(int|long|bool|uint|hwnd|string|Wstring|float|double|word|dword|byte|char|pchar|Wchar|pWchar|boolean|longlong|Extended|SafeArray))?\s*:\s*((\w+)(\.dll)?)</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.dll.uwsc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.dllfile.uwsc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.dll.type.uwsc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(int|long|bool|uint|hwnd|string|Wstring|float|double|word|dword|byte|char|pchar|Wchar|pWchar|boolean|longlong|Extended|SafeArray)\b</string>
					<key>name</key>
					<string>constant.language.dll.uwsc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?i)(\btextblock\b)\s+(([^/]*html[^/]*)(//.*)?|(([^/]+)(//.*html.*)))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.textblock.uwsc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.textblock.uwsc</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment.block.uwsc</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.textblock.uwsc</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>comment.block.uwsc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>textblock宣言 HTML</string>
			<key>end</key>
			<string>^\s*(?i)(\bendtextblock\b)</string>
			<key>name</key>
			<string>meta.textblock.html.uwsc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?i)(\btextblock\b)\s+(([^/]*json[^/]*)(//.*)?|(([^/]+)(//.*json.*)))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.textblock.uwsc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.textblock.uwsc</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment.block.uwsc</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.textblock.uwsc</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>comment.block.uwsc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>textblock宣言 JavaScript</string>
			<key>end</key>
			<string>^\s*(?i)(\bendtextblock\b)</string>
			<key>name</key>
			<string>meta.textblock.json.uwsc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.json</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?i)(\btextblock\b)\s+(([^/]*js[^/]*)(//.*)?|(([^/]+)(//.*js.*)))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.textblock.uwsc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.textblock.uwsc</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment.block.uwsc</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.textblock.uwsc</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>comment.block.uwsc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>textblock宣言 JavaScript</string>
			<key>end</key>
			<string>^\s*(?i)(\bendtextblock\b)</string>
			<key>name</key>
			<string>meta.textblock.js.uwsc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?i)(\btextblock\b)\s+(([^/]*vbs[^/]*)(//.*)?|(([^/]+)(//.*vbs.*)))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.textblock.uwsc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.textblock.uwsc</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment.block.uwsc</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.textblock.uwsc</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>comment.block.uwsc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>textblock宣言 JavaScript</string>
			<key>end</key>
			<string>^\s*(?i)(\bendtextblock\b)</string>
			<key>name</key>
			<string>meta.textblock.vbs.uwsc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.vbs</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?i)(\btextblock\b)\s+(\w+)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.textblock.uwsc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.textblock.uwsc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>textblock宣言</string>
			<key>end</key>
			<string>^\s*(?i)(\bendtextblock\b)</string>
			<key>name</key>
			<string>meta.textblock.uwsc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.*</string>
					<key>name</key>
					<string>comment.block.uwsc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(class|module)\s+(\w+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.module.uwsc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.uwsc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*end(class|module)</string>
			<key>name</key>
			<string>meta.module.uwsc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i:\b(GLOBAL|THIS)\b)</string>
					<key>name</key>
					<string>variable.parameter.uwsc</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.uwsc</string>
	<key>uuid</key>
	<string>0f466014-285a-4612-b00a-32866f2d6e6d</string>
</dict>
</plist>
